
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

package lexico.sintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CADENA = 9;
  public static final int OP_RESTA = 4;
  public static final int OP_SUMA = 3;
  public static final int ENTERO = 8;
  public static final int OP_MULT = 5;
  public static final int SEMI = 2;
  public static final int EOF = 0;
  public static final int PARENTESIS_IZQUIERDO = 6;
  public static final int PARENTESIS_DERECHO = 7;
  public static final int error = 1;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "OP_SUMA",
  "OP_RESTA",
  "OP_MULT",
  "PARENTESIS_IZQUIERDO",
  "PARENTESIS_DERECHO",
  "ENTERO",
  "CADENA"
  };
}

